title: Los Santos Fire Department - Statewide Scanner
baseURL: ""
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: North Los Santos
      description: Areas of Vinewood, Vinewood Hills, Rockford Hills, Morningwood,
        Richman, Backlot City and Mirror Park.
    - name: East Los Santos
      description: Areas of Le Masa, Murrieta Oil Field, Eastern Los Santos County.
    - name: South Los Santos
      description: Areas of the Port of Los Santos, Districts of Carson, Grove and
        Innocence & LISA.
    - name: West Los Santos
      description: Areas of Vespucci, Del Perro and Western Los Santos County.
    - name: Blaine County
      description: Covering everything above the Great Chaparral, Harmony, Grand
        Senora Desert, Sandy Shores and Paleto Bay.
  dateFormat: 2 January 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " (( servertime ))"
  logo: "/images/logo.png"
  description_header: Blahblah
  copyrightHolder: GTA:W
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: GTA WORLD is not affiliated with or endorsed by Rockstar
    North, Take-Two Interactive or other rightsholders. Any trademarks used
    belong to their respective owners. GTA WORLD reserves all rights on rightly
    owned images and other visual content provided on GTA.WORLD.
